platform :ios, '13.0'
use_frameworks!

target 'Example-ZFramework' do
  pod 'Alamofire', '~> 5.2'
  
  pod 'ModuleCommon', :path => './ModuleCommon'
  pod 'ModuleUser', :path => './ModuleUser'
  pod 'ModuleA', :path => './ModuleA'
  pod 'ModuleLogin', :path => './ModuleLogin'
end
